name: VyOS ISO integration Test

on:
  push:
  pull_request_target:
    branches:
      - current
      - circinus

permissions:
  pull-requests: write
  contents: read

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed for PR comments

jobs:
  build:
    runs-on: ubuntu-24.04
    timeout-minutes: 45
    # container:
    #   image: vyos/vyos-build:current
    #   options: --sysctl net.ipv6.conf.lo.disable_ipv6=0 --privileged
    env:
      BUILD_BY: autobuild@vyos.net
      DEBIAN_MIRROR: http://deb.debian.org/debian/
    outputs:
      build_version: ${{ steps.version.outputs.build_version }}
    steps:
      - name: Clone vyos-build source code
        uses: actions/checkout@v4
        with:
          repository: vyos/vyos-build
      - name: Clone vyos-1x source code
        uses: actions/checkout@v4
        with:
          path: packages/vyos-1x
      - name: Build vyos-1x package
        run: |
          ls -al ; ls -al packages/vyos-1x
      #     cd packages/vyos-1x; dpkg-buildpackage -uc -us -tc -b
      # - name: Generate ISO version string
      #   id: version
      #   run: |
      #     echo "build_version=1.5-integration-$(date -u +%Y%m%d%H%M)" >> $GITHUB_OUTPUT
      # - name: Build custom ISO image
      #   run: |
      #     sudo --preserve-env ./build-vyos-image \
      #     --architecture amd64 \
      #     --build-by $BUILD_BY \
      #     --debian-mirror $DEBIAN_MIRROR \
      #     --version ${{ steps.version.outputs.build_version }} \
      #     --build-type release \
      #     generic
      # - uses: actions/upload-artifact@v4
      #   with:
      #     name: vyos-${{ steps.version.outputs.build_version }}
      #     path: build/live-image-amd64.hybrid.iso

  cli-smoketests:
    needs: build
    runs-on: ubuntu-24.04
    timeout-minutes: 180
    # container:
    #   image: vyos/vyos-build:current
    #   options: --sysctl net.ipv6.conf.lo.disable_ipv6=0 --privileged
    outputs:
      result: ${{ steps.test.outputs.error_message }}
      exit_code: ${{ steps.test.outputs.exit_code }}
    steps:
      # We need the test script from vyos-build repo
      # - name: Clone vyos-build source code
      #   uses: actions/checkout@v4
      #   with:
      #     repository: vyos/vyos-build
      # - uses: actions/download-artifact@v4
      #   with:
      #     name: vyos-${{ needs.build.outputs.build_version }}
      #     path: build
      - name: VyOS CLI smoketests
        id: test
        run: |
          set +e
          #sudo make test
          ls -al | tee foo.log
          output=$(cat foo.log)

          asdf
          exit_code=$?
          set -e

          echo "exit_code=$exit_code" >> $GITHUB_OUTPUT
          echo "error_message=$output" >> $GITHUB_OUTPUT

          exit $exit_code

  config-load-tests:
    needs: build
    runs-on: ubuntu-24.04
    timeout-minutes: 90
    # container:
    #   image: vyos/vyos-build:current
    #   options: --sysctl net.ipv6.conf.lo.disable_ipv6=0 --privileged
    outputs:
      result: ${{ steps.test.outputs.error_message }}
      exit_code: ${{ steps.test.outputs.exit_code }}
    steps:
      # We need the test script from vyos-build repo
      # - name: Clone vyos-build source code
      #   uses: actions/checkout@v4
      #   with:
      #     repository: vyos/vyos-build
      # - uses: actions/download-artifact@v4
      #   with:
      #     name: vyos-${{ needs.build.outputs.build_version }}
      #     path: build
      - name: VyOS config load tests
        id: test
        run: |
          set +e
          sudo make testc
          output=$(ls -al && uname -a && ps faux)
          exit_code=$?
          set -e

          echo "exit_code=$exit_code" >> $GITHUB_OUTPUT
          echo "error_message=$output" >> $GITHUB_OUTPUT

          exit $exit_code

  raid1-install-test:
    needs: build
    runs-on: ubuntu-24.04
    timeout-minutes: 20
    # container:
    #   image: vyos/vyos-build:current
    #   options: --sysctl net.ipv6.conf.lo.disable_ipv6=0 --privileged
    outputs:
      result: ${{ steps.test.outputs.error_message }}
      exit_code: ${{ steps.test.outputs.exit_code }}
    steps:
      # We need the test script from vyos-build repo
      # - name: Clone vyos-build source code
      #   uses: actions/checkout@v4
      #   with:
      #     repository: vyos/vyos-build
      # - uses: actions/download-artifact@v4
      #   with:
      #     name: vyos-${{ needs.build.outputs.build_version }}
      #     path: build
      - name: VyOS RAID1 installation tests
        run: |
          set +e
          # sudo make testraid
          output=$(ls -al && uname -a && ps faux)
          exit_code=$?
          set -e

          echo "exit_code=$exit_code" >> $GITHUB_OUTPUT
          echo "error_message=$output" >> $GITHUB_OUTPUT

          exit $exit_code

  results:
    needs:
      - cli-smoketests
      - config-load-tests
      - raid1-install-test
    runs-on: ubuntu-24.04
    timeout-minutes: 90
    if: always()
    # container:
    #   image: vyos/vyos-build:current
    #   options: --sysctl net.ipv6.conf.lo.disable_ipv6=0 --privileged
    steps:
      # We need the test script from vyos-build repo
      # - name: Clone vyos-build source code
      #   uses: actions/checkout@v4
      #   with:
      #     repository: vyos/vyos-build
      # - uses: actions/download-artifact@v4
      #   with:
      #     name: vyos-${{ needs.build.outputs.build_version }}
      #     path: build
      - name: Add PR comment
        if: always()
        uses: mshick/add-pr-comment@v2
        with:
          message: |-
            ${{ needs.cli-smoketests.outputs.exit_code == '0' && needs.config-load-tests.outputs.exit_code == '0' && '👍 CI integration passed' || '❌ CI integration failed' }}

            <details>

            ## CLI Smoketests

            ${{ needs.cli-smoketests.outputs.result }}

            ## Config tests

            ${{ needs.config-load-tests.outputs.result }}

            ## RAID1 tests

            ${{ needs.raid1-install-test.outputs.result }}

            </details>
          message-id: "SMOKETEST_RESULTS"
          allow-repeats: false
          refresh-message-position: true
